package com.clientapp.enums;

public enum RequestType {
    SCREEN_CAPTURE,
    SYSTEM_INFO,
    PROCESS_LIST,
    COMMAND,
    PERFORMANCE_INFO,
    CPU_INFO,
    FILE_TRANSFER,
    CONNECTION,
    EXIT_PROCESS,
    EXIT_PERFORMANCE_INFO,
    EXIT_CPU_INFO,
    EXIT_SCREEN_CAPTURE,
    EXIT_COMMNAD_SCREEN
}