package com.serverapp.enums;

public enum RequestType {
    SCREEN_CAPTURE,
    SYSTEM_INFO,
    PROCESS_LIST,
    COMMAND,
    PERFORMANCE_INFO,
    CPU_INFO,
    CONNECTION,
    EXIT_PROCESS,
    EXIT_PERFORMANCE_INFO,
    EXIT_CPU_INFO,
    EXIT_SCREEN_CAPTURE,
    EXIT_COMMNAD_SCREEN,
    DETECT_MALWARE,
    STOP_DETECT_MALWARE,
    START_SCREEN_CAPTURE,
    PAUSE_SCREEN_CAPTURE
}