---
- name: Deploy JavaFX Applications
  hosts: all
  become: yes

  tasks:
    - name: Install Java Development Kit
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install JavaFX
      get_url:
        url: https://download2.gluonhq.com/openjfx/19.0.1/openjfx-19.0.1_linux-x64_bin-sdk.zip
        dest: /tmp/javafx-sdk.zip

    - name: Unzip JavaFX SDK
      unarchive:
        src: /tmp/javafx-sdk.zip
        dest: /opt/
        remote_src: yes

    - name: Copy server application JAR
      copy:
        src: /path/to/your-app-server.jar
        dest: /home/serveruser/your-app.jar
        mode: '0644'
        owner: serveruser

    - name: Copy client application JAR
      copy:
        src: /path/to/your-app-client.jar
        dest: /home/clientuser/your-app.jar
        mode: '0644'
        owner: clientuser

    - name: Set up and run the server application
      command: /home/serveruser/start_server.sh

    - name: Set up and run the client application
      command: /home/clientuser/start_client.sh
